lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.key'
    public_key: '%kernel.project_dir%/config/jwt/public.key'
    token_ttl: 3600
    user_identity_field: email
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS256